### PR TITLE
Added pbzip2 parallel decompression support

### PR DESCRIPTION
**Pull request by 0rinsb3lt**
Fixed pull request to just include pbzip2

### CODE REVIEW

**Comment by tritonas00** [comment]
please edit:

`$BRmcore` to `"$BRmcore"`
`${BRreadopts}` to `"$BRreadopts"`

and its ok.

of course we need to add extra check for pbizp2 package existence and update the help page and gui

i will apply the PR and do the extra work when i have my laptop

**Comment by 0rinsb3lt** [comment]
I used `${BRreadopts}` because it wouldn't work with just the quotes or with quotes and brackets due to the multiple hyphens. I have tested both conditions.

**Comment by tritonas00** [comment]
lines 500-501 are wrong

**Comment by 0rinsb3lt** [comment]
I've tested `"$BRreadopts"` but it doesn't work. It'll spit out errors.
Probably be better to convert it to an array like  `BR_MAIN_OPTS`
Due to the way bash handles passing variables to commands as parameters with spaces.

**Comment by tritonas00** [comment]
Ok then

**Comment by tritonas00** [comment]
please quote BRreadopts array and convert BR_MAIN_OPTS to array also here https://github.com/tritonas00/system-tar-and-restore/blob/master/star.sh#L909

**Comment by tritonas00** [comment]
https://github.com/tritonas00/system-tar-and-restore/pull/16/files#diff-d81e078b6c1696d08435d922909a863dR763 should be `xvpfz` (missing x)

**Comment by tritonas00** [comment]
looks good!

**Pull request merged**
